# uncompyle6 version 2.9.10
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.10 (default, Feb  6 2017, 23:53:20) 
# [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
# Embedded file name: __init__.py
ERR_SUCCESS = 0
ERR_INVALID_PARAMETER = 4294967287L
ERR_UNSUPPORTED_PLATFORM = 4294967286L
ERR_EXCEPTION = 4294967285L
ERR_GET_LOCK_FAILED = 4294967282L
ERR_MDL_CREATE_FAILED = 4294967276L
ERR_MDL_LOCK_FAILED = 4294967275L
ERR_SETUP_FAILED_1 = 4294967272L
ERR_SETUP_FAILED_2 = 4294967271L
ERR_SETUP_FAILED_3 = 4294967270L
ERR_SETUP_FAILED_4 = 4294967269L
ERR_SETUP_FAILED_5 = 4294967268L
ERR_EXPLOIT_FAILED = 4294967264L
ERR_EXPLOIT_NOT_AVAILABLE = 4294967263L
ERR_EXCEPTION_HANDLING_REQUIRED = 4294967262L
ERR_UNKNOWN = 4294967261L
errorStrings = {ERR_INVALID_PARAMETER: 'Invalid parameter(s)',
   ERR_UNSUPPORTED_PLATFORM: 'Unsupported platform',
   ERR_EXCEPTION: 'Exception thrown',
   ERR_GET_LOCK_FAILED: 'Failed to get privilege lock',
   ERR_MDL_CREATE_FAILED: 'Failed to create MDL',
   ERR_MDL_LOCK_FAILED: 'Failed to lock MDL',
   ERR_SETUP_FAILED_1: 'Setup failed (stage 1)',
   ERR_SETUP_FAILED_2: 'Setup failed (stage 2)',
   ERR_SETUP_FAILED_3: 'Setup failed (stage 3)',
   ERR_SETUP_FAILED_4: 'Setup failed (stage 4)',
   ERR_SETUP_FAILED_5: 'Setup failed (stage 5)',
   ERR_EXPLOIT_FAILED: 'Exploit failed',
   ERR_EXPLOIT_NOT_AVAILABLE: 'Given exploit not available',
   ERR_EXCEPTION_HANDLING_REQUIRED: 'Exception handling is required and was not available',
   ERR_UNKNOWN: 'Unknown error'
   }